runtime: nodejs20
service: default

env_variables:
  NODE_ENV: production
  PORT: 8080
  GMAIL_USER: "keraaigpt.plus@gmail.com"
  GMAIL_PASS: "tnev ssds hcpx evrw"
  DB_HOST: "34.31.155.251"
  DB_PORT: "3306"
  DB_USER: "pando-mysql"
  DB_PASSWORD: "Junior.28"
  DB_NAME: "pando_db"
  SESSION_SECRET: "kera-ai-secret-key-2024"
  ALLOWED_ORIGINS: "https://lwpdevelopers.online,https://www.lwpdevelopers.online"

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 3

resources:
  cpu: 1
  memory_gb: 0.5

inbound_services:
  - warmup

handlers:
  - url: /.*
    script: auto
    secure: always
    redirect_http_response_code: 301
