runtime: nodejs20
service: default

env_variables:
  NODE_ENV: production
  PORT: 8080
  GMAIL_USER: "keraaigpt.plus@gmail.com"
  GMAIL_PASS: "tnev ssds hcpx evrw"
  
  # Configuración de Google Cloud SQL MySQL - CORREGIDA
  GOOGLE_CLOUD_PROJECT: "luminous-style-465017-v6"
  CLOUD_SQL_CONNECTION_NAME: "luminous-style-465017-v6:us-central1:pando-mysql"
  CLOUD_SQL_PUBLIC_IP: "34.31.155.251"
  DB_HOST: "34.31.155.251"
  DB_PORT: "3306"
  DB_USER: "pando-mysql"
  DB_PASSWORD: "Junior.28"
  DB_NAME: "pando_db"
  
  # Configuración de seguridad
  SESSION_SECRET: "kera-ai-secret-key-2024"
  MAX_EMAILS_PER_HOUR: "50"
  MAX_EMAILS_PER_DAY: "500"
  
  # Configuración de CORS
  ALLOWED_ORIGINS: "https://lwpdevelopers.online,https://www.lwpdevelopers.online"
  CUSTOM_DOMAIN: "lwpdevelopers.online"
  FORCE_HTTPS: "true"

# Configuración automática de instancias
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 5

# Recursos del servidor
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

# Configuración de Cloud SQL Proxy - ACTUALIZADA
beta_settings:
  cloud_sql_instances: "luminous-style-465017-v6:us-central1:pando-mysql"

# Manejadores de URL
handlers:
  - url: /.*
    script: auto
    secure: always

# Servicios adicionales
inbound_services:
  - warmup
